<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SHOP')?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('css/jquery.bxslider.css'))


            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))  ?>

        <link href="/css/style.css" rel="stylesheet">

        <!-- Scripts -->
        <script   src="https://code.jquery.com/jquery-2.2.3.min.js"   integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo="   crossorigin="anonymous"></script>
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
//            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/scripts.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <link href='https://fonts.googleapis.com/css?family=Poiret+One&subset=latin,cyrillic' rel='stylesheet' type='text/css'>


    </head>
    <body>
        <nav class="navbar navbar-inverse " role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Главная') ?></a></li>
                        <li class="nav-hover"><a href="<?php echo $this->url('catalog') ?>" ><?php echo $this->translate('Товары') ?></a></li>

                        <li><a href="<?php echo $this->url('aandq') ?>"><?php echo $this->translate('Вопросы и ответы') ?></a></li>
                        <li><a href="<?php echo $this->url('reviews') ?>"><?php echo $this->translate('Отзывы') ?></a></li>
                    </ul>
                    <ul class="hover-menu" >
                        <li><a href="<?php echo $this->url('Nike') ?>">Nike</a></li>
                        <li><a href="#">Adidas</a></li>
                        <li><a href="#">Asics</a></li>
                        <li><a href="#">NewBalance</a></li>
                        <li><a href="#">Reebok</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            
            <footer id="footer">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse">
                            <a target="_blank" href="https://vk.com/spockew">VK</a>
                            <p>tvoijesus@gmail.com</p>
                            <p>0961411281</p>
                            <p>0933294381</p>
                        </div><!--/.nav-collapse -->
                    </div>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>