
   <script src="/js/jquery.min.js"></script>
   <script src="/js/jquery.bxslider.min.js"></script>
   



<div id="wrapper">
   <div id="gradient">
      <div class="main-page-title">
         <h1>Добро пожаловать в My shop</h1>
         <p>Самые низкие цены, самая быстрая доставка,</br>скидки постоянным клиентам</p>
         <a href="<?= $this->url('catalog')?>">ВСЕ ТОВАРЫ</a>
         <div class="slider">
               <ul class="bxslider">
                  <li><img src="/img/pic1.jpg" alt=""/></li>
                  <li><img src="/img/pic2.jpg" alt=""/></li>
                  <li><img src="/img/pic3.jpg" alt=""/></li>
               </ul>
            </div>
<!--         <div class="post-slider">-->
<!--         <h2>Акционные товары</h2>-->
<!--            </div>-->
         </div>
      </div>
   </div>
